#!/usr/bin/env python3
"""Offline analysis of the v0.1.1 archives: tables (CSV + Markdown) and figures (PDF/PNG).

Usage: python validation/analyze_v011.py validation/v0.1.1/mock [--live validation/v0.1.1/live-src-v1 ...] [--figdir figures]
Nothing here talks to ROS; everything is computed from the archived JSON.  The decision rule reproduced here is
the released one (probes/base.py decide(), including the 1e-9 boundary guard), applied to the archived
confidence intervals for the tolerance sweeps.
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from crtk_conformance import geometry as G  # noqa: E402
from crtk_conformance.probes.base import decide as _decide, Outcome  # noqa: E402

C_BLUE, C_ORANGE, C_GREEN, C_PINK, C_GREY = "#0072B2", "#E69F00", "#009E73", "#CC79A7", "#6e6e6e"


def load(d, prefix):
    out = []
    for f in sorted(glob.glob(os.path.join(d, prefix + "*.json"))):
        with open(f) as fh:
            out.append((os.path.basename(f)[:-5], json.load(fh)))
    return out


def decide(lo, hi, eps):
    if lo is None or hi is None:
        return "undetermined"
    return _decide(float(lo), float(hi), eps).value


def sweep(records, eps_grid):
    rows = []
    for eps in eps_grid:
        pos = neg = fp = fn = und = 0
        for truth, lo, hi in records:
            label_pos = truth > eps
            d = decide(lo, hi, eps)
            if label_pos:
                pos += 1
                fn += d == "conformant"
            else:
                neg += 1
                fp += d == "divergent"
            und += d == "undetermined"
        rows.append({"eps_mm": eps * 1e3, "positives": pos, "negatives": neg, "FP": fp, "FN": fn, "undetermined": und,
                     "FPR": fp / neg if neg else float("nan"), "FNR": fn / pos if pos else float("nan"), "undetermined_rate": und / len(records)})
    return rows


def write_csv(path, rows):
    if not rows:
        return
    keys = list(rows[0].keys())
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def fmt(v, nd=3):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "—"
    return f"{v:.{nd}f}" if isinstance(v, float) else str(v)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("archive")
    ap.add_argument("--live", nargs="*", default=[])
    ap.add_argument("--figdir", default=None)
    args = ap.parse_args()
    d = args.archive
    tdir = os.path.join(d, "tables")
    os.makedirs(tdir, exist_ok=True)
    figdir = args.figdir or tdir
    os.makedirs(figdir, exist_ok=True)
    md = ["# v0.1.1 mock validation — summary tables (generated by analyze_v011.py; every number from the archived JSON)", ""]
    meta = json.load(open(os.path.join(d, "meta.json")))
    md.append(f"Archive: commit {meta['repo_commit'][:12]}, {meta['started_at']} → {meta['finished_at']}, wall {meta['wall_s']/60:.1f} min, "
              f"Python {meta['python'].split()[0]}, numpy {meta['numpy']}, scipy {meta['scipy']}, container {meta.get('container_image')} ({str(meta.get('container_digest'))[:19]}).")
    md.append("")
    false_conformant = []

    # ------------------------------------------------------------------ F identity grid
    frows, frec = [], []
    for name, r in load(d, "F_id_"):
        tr, res, est = r["truth"], r["result"], r["result"]["estimates"]
        t_hat = np.array(est.get("binding_translation_m", [np.nan] * 3))
        t_true = np.array(tr["t_m"])
        th_hat = est.get("binding_rotation_deg", {}).get("mean", float("nan"))
        pe = est.get("predicted_abs_error_at_workspace_edge_m", {})
        row = {"run": name, "t_true_mm": tr["t_norm_m"] * 1e3, "theta_true_deg": tr["theta_deg"], "noise_mm": tr["noise_m"] * 1e3,
               "t_hat_mm": float(np.linalg.norm(t_hat)) * 1e3, "t_err_mm": float(np.linalg.norm(t_hat - t_true)) * 1e3,
               "theta_hat_deg": th_hat, "theta_err_deg": abs(th_hat - tr["theta_deg"]) if not math.isnan(th_hat) else float("nan"),
               "model_error_mm": tr["model_error_m"] * 1e3, "pred_mm": pe.get("mean", float("nan")) * 1e3 if pe else float("nan"),
               "ci_low_mm": pe.get("ci_low", float("nan")) * 1e3 if pe else float("nan"), "ci_high_mm": pe.get("ci_high", float("nan")) * 1e3 if pe else float("nan"),
               "outcome": res["outcome"], "unpaired": est.get("unpaired_samples")}
        frows.append(row)
        frec.append((tr["model_error_m"], pe.get("ci_low"), pe.get("ci_high")))
        if res["outcome"] == "conformant" and tr["model_error_m"] > 0.001:
            false_conformant.append(name)
    write_csv(os.path.join(tdir, "F_id_runs.csv"), frows)
    fsum = []
    for noise in sorted({r["noise_mm"] for r in frows}):
        sub = [r for r in frows if r["noise_mm"] == noise]
        zero = [r for r in sub if r["t_true_mm"] == 0 and r["theta_true_deg"] == 0]
        fsum.append({"noise_mm": noise, "runs": len(sub), "t_err_mean_mm": float(np.mean([r["t_err_mm"] for r in sub])), "t_err_max_mm": float(np.max([r["t_err_mm"] for r in sub])),
                     "theta_err_max_deg": float(np.max([r["theta_err_deg"] for r in sub])), "floor_t_hat_at_zero_mm": zero[0]["t_hat_mm"] if zero else float("nan"),
                     "conformant": sum(r["outcome"] == "conformant" for r in sub), "divergent": sum(r["outcome"] == "divergent" for r in sub), "undetermined": sum(r["outcome"] == "undetermined" for r in sub)})
    write_csv(os.path.join(tdir, "F_id_summary.csv"), fsum)
    eps_grid = np.logspace(math.log10(0.05e-3), math.log10(50e-3), 61)
    fsweep = sweep(frec, eps_grid)
    write_csv(os.path.join(tdir, "F_id_threshold_sweep.csv"), fsweep)
    md += ["## Frame probe, identity expectation (F_id, %d runs)" % len(frows), "", "| noise (mm) | runs | mean ‖t̂−t‖ (mm) | max ‖t̂−t‖ (mm) | max |θ̂−θ| (deg) | floor ‖t̂‖ at t=0 (mm) | conformant / divergent / undetermined at ε = 1 mm |", "|---|---|---|---|---|---|---|"]
    for r in fsum:
        md.append(f"| {r['noise_mm']:g} | {r['runs']} | {r['t_err_mean_mm']:.4f} | {r['t_err_max_mm']:.4f} | {r['theta_err_max_deg']:.2e} | {r['floor_t_hat_at_zero_mm']:.4f} | {r['conformant']} / {r['divergent']} / {r['undetermined']} |")
    fp_max = max(r["FP"] for r in fsweep); fn_max = max(r["FN"] for r in fsweep); und_max = max(r["undetermined"] for r in fsweep)
    md.append(f"\nTolerance sweep 0.05–50 mm (61 points): max FP {fp_max}, max FN {fn_max}, max undetermined {und_max} of {len(frec)} " +
              ("(" + "; ".join(f"ε={r['eps_mm']:.3g} mm: FP {r['FP']} FN {r['FN']} und {r['undetermined']}" for r in fsweep if r['FP'] or r['FN']) + ")" if (fp_max or fn_max) else "") + ".")
    md.append("")
    # other frame cases
    md += ["| frame case | injected | expectation | outcome | ‖t̂‖ (mm) | θ̂ (deg) | residual (mm) | pred. error CI (mm) | note |", "|---|---|---|---|---|---|---|---|---|"]
    fx = []
    for prefix in ("F_exp_", "F_expwrong_", "F_disc_", "F_nolocal", "F_orient_", "F_skew_"):
        for name, r in load(d, prefix):
            tr, res, est = r["truth"], r["result"], r["result"]["estimates"]
            pe = est.get("predicted_abs_error_at_workspace_edge_m")
            row = {"run": name, "truth": json.dumps(tr), "expectation": r["expectation"]["spatial"]["mode"], "outcome": res["outcome"],
                   "t_hat_mm": est.get("binding_translation_norm_m", {}).get("mean", float("nan")) * 1e3 if est.get("binding_translation_norm_m") else float("nan"),
                   "theta_hat_deg": est.get("binding_rotation_deg", {}).get("mean", float("nan")) if est.get("binding_rotation_deg") else float("nan"),
                   "residual_mm": est.get("residual_translation_norm_m", float("nan")) * 1e3 if "residual_translation_norm_m" in est else float("nan"),
                   "ci_mm": f"{pe['ci_low']*1e3:.3f}..{pe['ci_high']*1e3:.3f}" if pe else "—", "unpaired": est.get("unpaired_samples"), "basis": res["decision_basis"][:80]}
            fx.append(row)
            md.append(f"| {name} | {row['truth'][:60]} | {row['expectation']} | {res['outcome']} | {fmt(row['t_hat_mm'])} | {fmt(row['theta_hat_deg'])} | {fmt(row['residual_mm'])} | {row['ci_mm']} | {row['basis'][:60]} |")
            if res["outcome"] == "conformant" and (r["expectation"]["spatial"]["mode"] == "discover_only" or tr.get("model_residual_m", 0) > 0.001):
                false_conformant.append(name)
    write_csv(os.path.join(tdir, "F_cases.csv"), fx)
    md.append("")

    # ------------------------------------------------------------------ S
    srows, srec = [], []
    for name, r in load(d, "S_si_"):
        tr, res, est = r["truth"], r["result"], r["result"]["estimates"]
        sa = est.get("scale_anchored", {})
        pe = est.get("predicted_error_at_workspace_edge_m", {})
        row = {"run": name, "s_true": tr["s"], "noise_mm": tr["noise_m"] * 1e3, "r_int_mean": est["internal_ratio"]["mean"], "s_hat_mean": sa.get("mean", float("nan")),
               "s_hat_rel_err": abs(sa.get("mean", float("nan")) - tr["s"]) / tr["s"], "s_hat_ci_low": sa.get("ci_low"), "s_hat_ci_high": sa.get("ci_high"),
               "model_error_mm": tr["model_error_m"] * 1e3, "outcome": res["outcome"], "valid_trials": r["result"]["observations"].get("valid_trials"),
               "latency_ms": est.get("response_latency_s", {}).get("mean", float("nan")) * 1e3 if est.get("response_latency_s") else float("nan")}
        srows.append(row)
        srec.append((tr["model_error_m"], pe.get("ci_low"), pe.get("ci_high")))
        if res["outcome"] == "conformant" and tr["model_error_m"] > 0.001:
            false_conformant.append(name)
    write_csv(os.path.join(tdir, "S_si_runs.csv"), srows)
    ssweep = sweep(srec, eps_grid)
    write_csv(os.path.join(tdir, "S_si_threshold_sweep.csv"), ssweep)
    md += ["## Scale probe, SI expectation with anchor (S_si, %d runs)" % len(srows), "", "| noise (mm) | runs | r_int mean (min–max) | max rel. error of ŝ | conformant / divergent / undetermined at ε = 1 mm |", "|---|---|---|---|---|"]
    for noise in sorted({r["noise_mm"] for r in srows}):
        sub = [r for r in srows if r["noise_mm"] == noise]
        md.append(f"| {noise:g} | {len(sub)} | {np.mean([r['r_int_mean'] for r in sub]):.4f} ({min(r['r_int_mean'] for r in sub):.4f}–{max(r['r_int_mean'] for r in sub):.4f}) | {100*max(r['s_hat_rel_err'] for r in sub):.2f} % | "
                  f"{sum(r['outcome']=='conformant' for r in sub)} / {sum(r['outcome']=='divergent' for r in sub)} / {sum(r['outcome']=='undetermined' for r in sub)} |")
    fp_max = max(r["FP"] for r in ssweep); fn_max = max(r["FN"] for r in ssweep); und_max = max(r["undetermined"] for r in ssweep)
    md.append(f"\nTolerance sweep: max FP {fp_max}, max FN {fn_max}, max undetermined {und_max} of {len(srec)}.")
    md += ["", "| scale case | truth | expectation | outcome | r_int | ŝ | valid / no-response trials | basis |", "|---|---|---|---|---|---|---|---|"]
    sx = []
    for prefix in ("S_noanchor", "S_disc", "S_unit01", "S_anchornoise_", "S_drop_"):
        for name, r in load(d, prefix):
            tr, res, est, obs = r["truth"], r["result"], r["result"]["estimates"], r["result"]["observations"]
            row = {"run": name, "truth": json.dumps(tr), "expectation": r["expectation"]["dimensional"]["mode"], "outcome": res["outcome"], "r_int": est.get("internal_ratio", {}).get("mean"),
                   "s_hat": est.get("scale_anchored", {}).get("mean"), "valid_trials": obs.get("valid_trials"), "no_response": obs.get("no_response_trials"), "basis": res["decision_basis"][:90]}
            sx.append(row)
            md.append(f"| {name} | {row['truth'][:50]} | {row['expectation']} | {res['outcome']} | {fmt(row['r_int'], 4)} | {fmt(row['s_hat'], 4)} | {row['valid_trials']} / {row['no_response']} | {row['basis'][:70]} |")
            if res["outcome"] == "conformant" and (r["expectation"]["dimensional"]["mode"] == "discover_only" or tr.get("model_error_m", 0) > 0.001):
                false_conformant.append(name)
    write_csv(os.path.join(tdir, "S_cases.csv"), sx)
    md.append("")

    # ------------------------------------------------------------------ T rate
    trows = []
    viol = 0
    for prefix in ("T_rate_", "T_interp_", "T_drop_", "T_delay_"):
        for name, r in load(d, prefix):
            tr, res = r["truth"], r["result"]
            for row in res["observations"]["effective_rate"]["per_rate"]:
                viol += row["transitions"] > row["commands_sent"]
                trows.append({"run": name, "truth": json.dumps(tr), "requested_hz": row["command_rate_requested_hz"], "commands": row["commands_sent"], "transitions": row["transitions"],
                              "observable_hz": row["observable_rate_hz"], "client_achieved_hz": row["client_rate_achieved_hz"], "publish_hz": row["publish_rate_hz"],
                              "unmatched_fraction": row["unmatched_fraction"], "match_tol_mm": row["match_tolerance_m"] * 1e3, "step_mm": (row.get("step_used_m") if row.get("step_used_m") is not None else float("nan")) * 1e3,
                              "bounded_by": row["observation_bounded_by"], "status": row["status"], "note": row.get("note", ""), "outcome": res["outcome"]})
    write_csv(os.path.join(tdir, "T_rate_rows.csv"), trows)
    md += ["## Observable-rate sub-probe (%d rows; invariant transitions ≤ commands violated in %d rows)" % (len(trows), viol), "",
           "| run | condition | requested (Hz) | transitions / commands | observable (Hz) | client achieved (Hz) | publish (Hz) | unmatched | δ (mm) | bounded by | status |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in trows:
        md.append(f"| {r['run']} | {r['truth'][:45]} | {r['requested_hz']:.0f} | {r['transitions']} / {r['commands']} | {r['observable_hz']:.1f} | {r['client_achieved_hz']:.1f} | {r['publish_hz']:.1f} | {r['unmatched_fraction']:.2f} | {r['match_tol_mm']:.3f} | {r['bounded_by']} | {r['status']} |")
    md.append("")

    # ------------------------------------------------------------------ L liveness
    lrows = []
    for prefix in ("L_fault_", "L_release_", "L_hold", "L_delayed", "L_slowfb"):
        for name, r in load(d, prefix):
            tr, res = r["truth"], r["result"]
            L, R = res["observations"]["liveness"], res["observations"]["resolution"]
            tau = L.get("tau_w_estimate_s")
            lrows.append({"run": name, "tau_true_s": tr.get("tau_w_s"), "mode": tr.get("mode"), "floor_ms": R["resolution_floor_s"] * 1e3, "latency_p95_ms": R["response_latency_p95_s"] * 1e3 if R.get("response_latency_p95_s") is not None else float("nan"),
                          "response_timeout_s": R["response_timeout_s"], "stop_class": L.get("stop_class"),
                          "tau_hat_s": tau.get("mean") if isinstance(tau, dict) and "mean" in tau else None,
                          "tau_ci_low": tau.get("ci_low") if isinstance(tau, dict) else None, "tau_ci_high": tau.get("ci_high") if isinstance(tau, dict) else None,
                          "tau_status": (tau.get("status") if isinstance(tau, dict) and "status" in tau else ("upper_bound" if isinstance(tau, dict) and "upper_bound_s" in tau else "none")),
                          "tau_upper_bound_s": tau.get("upper_bound_s") if isinstance(tau, dict) else None, "n": tau.get("n") if isinstance(tau, dict) else None,
                          "trials_below_resolution": L.get("trials_below_resolution"), "outcome": res["outcome"], "finding": L.get("finding")})
            # a run whose injected stop policy is not the declared one must not be conformant (L_release_000, first campaign)
            inj = {"fault": "fault", "release": "release", "none": "no_policy_within_range"}.get(tr.get("mode") or "none")
            if res["outcome"] == "conformant" and (L.get("stop_class") != inj):
                false_conformant.append(name)
    write_csv(os.path.join(tdir, "L_liveness.csv"), lrows)
    md += ["## Liveness / stop behaviour (%d runs)" % len(lrows), "", "| run | injected τ_w (s) | mode | floor (ms) | stop class | τ̂_w (s) | 95 % CI | status | n | outcome |", "|---|---|---|---|---|---|---|---|---|---|"]
    for r in lrows:
        ci = f"{r['tau_ci_low']:.4f}..{r['tau_ci_high']:.4f}" if r["tau_ci_low"] is not None and r["tau_ci_high"] is not None and r["tau_status"] == "ok" else ("≤ %.4f" % r["tau_upper_bound_s"] if r["tau_upper_bound_s"] else "—")
        md.append(f"| {r['run']} | {r['tau_true_s']} | {r['mode']} | {r['floor_ms']:.1f} | {r['stop_class']} | {fmt(r['tau_hat_s'], 4)} | {ci} | {r['tau_status']} | {r['n']} | {r['outcome']} |")
    md.append("")

    # ------------------------------------------------------------------ P state
    prows = []
    for name, r in load(d, "P_state_"):
        tr, res, A = r["truth"], r["result"], r["result"]["observations"]["state_precondition"]
        en = A.get("enable") if isinstance(A.get("enable"), dict) else {}
        prows.append({"run": name, "preset": tr.get("preset"), "expect": tr.get("expect"), "state_topic": A.get("operating_state_present"), "executed_when_disabled": A.get("executed_when_disabled"),
                      "executed_when_enabled": A.get("executed_when_enabled"), "executed_without_sm": A.get("executed_without_state_machine"), "enable_latency_ms": en.get("enable_latency_s", float("nan")) * 1e3 if en.get("enable_latency_s") else float("nan"), "outcome": res["outcome"]})
    write_csv(os.path.join(tdir, "P_state.csv"), prows)
    md += ["## State precondition", "", "| run | preset | expectation | state topic | executed disabled / enabled / without SM | enable latency (ms) | outcome |", "|---|---|---|---|---|---|---|"]
    for r in prows:
        md.append(f"| {r['run']} | {r['preset']} | {r['expect']} | {r['state_topic']} | {r['executed_when_disabled']} / {r['executed_when_enabled']} / {r['executed_without_sm']} | {fmt(r['enable_latency_ms'], 1)} | {r['outcome']} |")
        if r["outcome"] == "conformant" and r["expect"] == "discover":
            false_conformant.append(r["run"])
    md.append("")

    # ------------------------------------------------------------------ R + presets
    md += ["## Regression cases (all classes declared)", "", "| case | spatial | dimensional | temporal | notes |", "|---|---|---|---|---|"]
    rrows = []
    for name, r in load(d, "R_"):
        oc = {x["binding_class"]: x["outcome"] for x in r["results"]}
        notes = "; ".join(n[:70] for x in r["results"] for n in x["notes"][:1])
        rrows.append({"case": name, **oc, "notes": notes})
        md.append(f"| {name} | {oc.get('spatial')} | {oc.get('dimensional')} | {oc.get('temporal')} | {notes[:120]} |")
        for x in r["results"]:
            if x["outcome"] == "conformant" and name in ("R_noisy",) and x["binding_class"] == "spatial":
                false_conformant.append(name)
    write_csv(os.path.join(tdir, "R_regression.csv"), rrows)
    md += ["", "## Presets (full reports)", "", "| preset | expectation | spatial | dimensional | temporal | frame ‖t̂‖ / θ̂ | ŝ | stop class |", "|---|---|---|---|---|---|---|---|"]
    xrows = []
    for name, rep in load(d, "PRESET_"):
        s = rep["summary"]
        fr = next((p for p in rep["probes"] if p["binding_class"] == "spatial"), {})
        sc = next((p for p in rep["probes"] if p["binding_class"] == "dimensional"), {})
        te = next((p for p in rep["probes"] if p["binding_class"] == "temporal"), {})
        fe = fr.get("estimates", {})
        row = {"preset": rep["parameters"]["preset"], "label": rep["parameters"]["label"], **s,
               "t_hat_mm": fe.get("binding_translation_norm_m", {}).get("mean", float("nan")) * 1e3 if fe.get("binding_translation_norm_m") else float("nan"),
               "theta_hat_deg": fe.get("binding_rotation_deg", {}).get("mean", float("nan")) if fe.get("binding_rotation_deg") else float("nan"),
               "s_hat": sc.get("estimates", {}).get("scale_anchored", {}).get("mean"), "stop_class": te.get("estimates", {}).get("stop_class")}
        xrows.append(row)
        md.append(f"| {row['preset']} | {row['label']} | {s['spatial']} | {s['dimensional']} | {s['temporal']} | {fmt(row['t_hat_mm'], 1)} / {fmt(row['theta_hat_deg'], 1)} | {fmt(row['s_hat'], 4)} | {row['stop_class']} |")
        if row["label"] == "discover" and "conformant" in s.values():
            false_conformant.append(name)
    write_csv(os.path.join(tdir, "PRESETS.csv"), xrows)
    md.append("")

    # ------------------------------------------------------------------ M
    mrows = []
    mm = load(d, "M_model_check")
    if mm:
        for c in mm[0][1]["cases"]:
            x = c.get("p_c_norm_m", c.get("step_m"))
            mrows.append({"kind": c["kind"], "x_mm": x * 1e3, "measured_mm": c["measured_error_m"] * 1e3, "predicted_mm": c["predicted_error_m"] * 1e3,
                          "bound_mm": c.get("upper_bound_m", float("nan")) * 1e3 if c.get("upper_bound_m") is not None else float("nan"), "abs_diff_mm": abs(c["measured_error_m"] - c["predicted_error_m"]) * 1e3})
        write_csv(os.path.join(tdir, "M_model_check.csv"), mrows)
        md += ["## Model check (mock executed error vs model prediction with T = base_frame⁻¹; implementation verification)", "", "| case | ‖p_c‖ or step (mm) | executed error (mm) | predicted (mm) | bound (mm) | |diff| (mm) |", "|---|---|---|---|---|---|"]
        for r in mrows:
            md.append(f"| {r['kind']} | {r['x_mm']:.1f} | {r['measured_mm']:.2f} | {r['predicted_mm']:.2f} | {fmt(r['bound_mm'], 2)} | {r['abs_diff_mm']:.3f} |")
        md.append(f"\nMax |executed − predicted| = {max(r['abs_diff_mm'] for r in mrows):.3f} mm over {len(mrows)} points.")
        md.append("")

    md += [f"## False conformant (general definition): {len(false_conformant)} run(s)" + (": " + ", ".join(false_conformant) if false_conformant else ""), ""]

    # ------------------------------------------------------------------ live
    for ld in args.live:
        tag = os.path.basename(ld.rstrip("/"))
        md += [f"## Live: {tag}", ""]
        aux_p = os.path.join(ld, "live_aux.json")
        if os.path.exists(aux_p):
            a = json.load(open(aux_p))
            pres = a["presence"]
            md.append("Topics: " + ", ".join(f"{k}={'yes' if v else 'no'}" for k, v in pres.items()) + f"; /tf {'yes' if a.get('tf_present') else 'no'}.")
            mc = a["measured_cp"]
            md.append(f"measured_cp: frame_id `{mc['frame_id']}`, publish rate {mc['rate_hz']:.1f} Hz (inter-arrival mean {mc['interarrival_s']['mean']*1e3:.2f} ms, max {mc['interarrival_s']['max']*1e3:.1f} ms).")
            if "T_b_w" in a:
                md.append(f"T_b_w: frame_id `{a['T_b_w']['frame_id']}`, translation {np.round(a['T_b_w']['pose'][:3], 4).tolist()} (interface units).")
            for k, v in a.get("joint_configs", {}).items():
                md.append(f"joint config {k}: commanded q {v['commanded_q']}; measured_js {np.round(v.get('measured_js_mean', []), 4).tolist()}; reported − simulated joints {np.round(v.get('reported_minus_simulated_joint', []), 4).tolist()}; ‖measured_cp‖ = {v.get('measured_cp_position_norm', float('nan')):.5f} interface units.")
            if "servo_cp_step" in a:
                s = a["servo_cp_step"]
                md.append(f"servo_cp step of {s['commanded_step_if_units']} (x): residual ‖measured − goal‖ = {s['residual_norm_if_units']:.4f} interface units after settling; measured std {np.round(s['measured_std'], 5).tolist()}.")
            md.append("")
        for rep_name in ("report_discover_only", "report_src_client", "report_dvrk_client"):
            p = os.path.join(ld, rep_name + ".json")
            if not os.path.exists(p):
                continue
            rep = json.load(open(p))
            md.append(f"**{rep_name}** (expectations: {rep['expectations']['source']}): summary {rep['summary']}")
            for pr in rep["probes"]:
                md.append(f"- {pr['binding_class']}: {pr['outcome']} — {pr['decision_basis'][:160]}")
                if pr["binding_class"] == "temporal":
                    o = pr["observations"]
                    R = o["resolution"]
                    md.append(f"  - resolution floor {R['resolution_floor_s']*1e3:.1f} ms, feedback period {R['feedback_period_s']*1e3:.2f} ms, resting noise σ̂ {R['resting_noise_sigma_m']:.2e} (interface units), response timeout {R['response_timeout_s']:.2f} s; state topic {o['state_precondition'].get('operating_state_present')}, executed without state machine {o['state_precondition'].get('executed_without_state_machine')} (attained {o['state_precondition'].get('attained_without_state_machine')})")
                    md.append(f"  - liveness: {o['liveness'].get('finding')}")
                    for row in o["effective_rate"]["per_rate"]:
                        md.append(f"  - rate {row['command_rate_requested_hz']:.0f} Hz: {row['transitions']}/{row['commands_sent']} transitions, observable {row['observable_rate_hz']:.1f} Hz, client {row['client_rate_achieved_hz']:.1f} Hz, publish {row['publish_rate_hz']:.1f} Hz, unmatched {row['unmatched_fraction']:.2f}, δ {row['match_tolerance_m']:.4g}, step {(row.get('step_used_m') if row.get('step_used_m') is not None else float('nan')):.4g}, {row['status']} ({row.get('reason') or row['observation_bounded_by']})")
                if pr["binding_class"] == "dimensional":
                    o = pr["observations"]
                    e = pr["estimates"]
                    md.append(f"  - internal ratio {e.get('internal_ratio', {}).get('mean', float('nan')):.4f} (95 % CI {e.get('internal_ratio', {}).get('ci_low', float('nan')):.3f}..{e.get('internal_ratio', {}).get('ci_high', float('nan')):.3f}, n = {e.get('internal_ratio', {}).get('n')}), step used {o.get('step_used_if')}, resting σ̂ {o.get('resting_noise_sigma_if')}, no-response trials {o.get('no_response_trials')}, latency {e.get('response_latency_s', {}).get('mean', float('nan'))*1e3:.1f} ms")
                if pr["binding_class"] == "spatial":
                    md.append(f"  - frame_ids {pr['observations'].get('frame_ids')}; T_b_w {pr['estimates'].get('T_b_w_translation_m')} / {pr['estimates'].get('T_b_w_rotation_deg')}")
            md.append("")

    with open(os.path.join(tdir, "SUMMARY.md"), "w") as f:
        f.write("\n".join(md))
    print("\n".join(md))

    # ------------------------------------------------------------------ figures
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False, "axes.grid": True, "grid.color": "#e6e6e6", "grid.linewidth": 0.5, "legend.frameon": False})
    fig, axs = plt.subplots(2, 2, figsize=(6.8, 5.2))
    markers = {0.0: "o", 0.02: "s", 0.1: "^"}
    cols = {0.0: C_BLUE, 0.02: C_ORANGE, 0.1: C_GREEN}
    ax = axs[0, 0]
    for noise in sorted({r["noise_mm"] for r in frows}):
        sub = [r for r in frows if r["noise_mm"] == noise and r["theta_true_deg"] == 0]
        ax.plot([max(r["t_true_mm"], 0.03) for r in sub], [max(r["t_err_mm"], 1e-5) for r in sub], marker=markers.get(noise, "o"), color=cols.get(noise, C_GREY), lw=1, ms=4, label=f"noise {noise:g} mm")
    ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("injected ‖t‖ (mm)  [θ = 0]"); ax.set_ylabel("‖t̂ − t‖ (mm)  (floor 1e-5)"); ax.set_title("(a) frame: translation estimate", loc="left"); ax.legend(fontsize=7)
    ax = axs[0, 1]
    for noise in sorted({r["noise_mm"] for r in srows}):
        sub = sorted([r for r in srows if r["noise_mm"] == noise], key=lambda r: r["s_true"])
        ax.plot([r["s_true"] for r in sub], [r["s_hat_mean"] for r in sub], marker=markers.get(noise, "o"), color=cols.get(noise, C_GREY), lw=1, ms=4, label=f"ŝ (anchored), noise {noise:g} mm")
        ax.plot([r["s_true"] for r in sub], [r["r_int_mean"] for r in sub], marker=markers.get(noise, "o"), mfc="none", color=cols.get(noise, C_GREY), lw=1, ls="--", ms=4)
    ax.plot([0.1, 10], [0.1, 10], color=C_GREY, lw=0.8, ls=":")
    ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("injected scale s"); ax.set_ylabel("estimate"); ax.set_title("(b) scale: anchored ŝ (solid), internal ratio (dashed)", loc="left", fontsize=7.5); ax.legend(fontsize=6.5)
    ax = axs[1, 0]
    ok = [r for r in lrows if r["tau_status"] == "ok" and r["mode"] == "fault"]
    if ok:
        ax.errorbar([r["tau_true_s"] for r in ok], [r["tau_hat_s"] for r in ok], yerr=[[r["tau_hat_s"] - r["tau_ci_low"] for r in ok], [r["tau_ci_high"] - r["tau_hat_s"] for r in ok]], fmt="o", color=C_BLUE, ms=4, capsize=2, lw=1, label="fault: τ̂_w (95 % CI)")
    ub = [r for r in lrows if r["tau_status"] == "upper_bound" and r["mode"] == "fault"]
    if ub:
        ax.plot([r["tau_true_s"] for r in ub], [r["tau_upper_bound_s"] for r in ub], "v", color=C_PINK, ms=5, label="below resolution: upper bound")
    rel = [r for r in lrows if r["tau_status"] == "ok" and r["mode"] == "release"]
    if rel:
        ax.errorbar([r["tau_true_s"] for r in rel], [r["tau_hat_s"] for r in rel], yerr=[[r["tau_hat_s"] - r["tau_ci_low"] for r in rel], [r["tau_ci_high"] - r["tau_hat_s"] for r in rel]], fmt="s", color=C_ORANGE, ms=4, capsize=2, lw=1, label="release: τ̂_w (95 % CI)")
    if lrows:
        fl = float(np.median([r["floor_ms"] for r in lrows])) / 1e3
        ax.axhline(fl, color=C_GREY, lw=0.8, ls="--", label=f"measured resolution floor ≈ {fl*1e3:.0f} ms")
    ax.plot([0.015, 1.2], [0.015, 1.2], color=C_GREY, lw=0.8, ls=":")
    ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("injected τ_w (s)"); ax.set_ylabel("estimated τ̂_w (s)"); ax.set_title("(c) liveness timeout estimate", loc="left"); ax.legend(fontsize=6.5)
    ax = axs[1, 1]
    ax.plot([r["eps_mm"] for r in fsweep], [r["FPR"] for r in fsweep], color=C_BLUE, lw=1.5, label="frame false-conformant")
    ax.plot([r["eps_mm"] for r in fsweep], [r["FNR"] for r in fsweep], color=C_BLUE, lw=1.5, ls="--", label="frame false-divergent")
    ax.plot([r["eps_mm"] for r in fsweep], [r["undetermined_rate"] for r in fsweep], color=C_BLUE, lw=1, ls=":", label="frame undetermined")
    ax.plot([r["eps_mm"] for r in ssweep], [r["FPR"] for r in ssweep], color=C_ORANGE, lw=1.5, label="scale false-conformant")
    ax.plot([r["eps_mm"] for r in ssweep], [r["FNR"] for r in ssweep], color=C_ORANGE, lw=1.5, ls="--", label="scale false-divergent")
    ax.plot([r["eps_mm"] for r in ssweep], [r["undetermined_rate"] for r in ssweep], color=C_ORANGE, lw=1, ls=":", label="scale undetermined")
    ax.set_xscale("log"); ax.set_xlabel("tolerance ε (mm)"); ax.set_ylabel("rate"); ax.set_ylim(-0.02, 1.02); ax.set_title("(d) decision rates vs. tolerance (identity declared)", loc="left"); ax.legend(fontsize=6.5, ncol=2)
    fig.tight_layout()
    fig.savefig(os.path.join(figdir, "fig05_validation.pdf")); fig.savefig(os.path.join(figdir, "fig05_validation.png"), dpi=200)

    # error-model figure: model with T = base_frame^-1 (JHU), mock points from M
    fig, axs = plt.subplots(1, 3, figsize=(6.8, 2.3))
    T_base = G.make_pose(G.axis_angle([1, 0, 0], math.radians(-150.0)), [0.20, 0, 0])
    Tm = G.invert(T_base); R, t = Tm[:3, :3], Tm[:3, 3]
    ps = np.linspace(0, 0.10, 101)
    ax = axs[0]
    ax.plot(ps * 1e3, [G.m1_positional_error(R, t, np.array([0, 0, p])) * 1e3 for p in ps], color=C_BLUE, lw=1.5, label="absolute, p⊥axis (eq. 1)")
    ax.plot(ps * 1e3, [G.m1_positional_error(R, t, np.array([p, 0, 0])) * 1e3 for p in ps], color=C_BLUE, lw=1.5, ls="--", label="absolute, p∥axis")
    ax.plot(ps * 1e3, [G.m1_upper_bound(R, t, p) * 1e3 for p in ps], color=C_GREY, lw=1, ls=":", label="bound (3)")
    ax.plot(ps * 1e3, [G.m1_incremental_bound(R, p) * 1e3 for p in ps], color=C_ORANGE, lw=1.5, label="incremental (5), step = ‖p‖")
    ax.plot(ps * 1e3, [0 for p in ps], color=C_ORANGE, lw=1.5, ls="--", label="incremental, R = I")
    for m in mrows:
        if m["kind"].startswith("absolute"):
            ax.plot(m["x_mm"], m["measured_mm"], "o", color=C_BLUE, ms=4, mfc="white")
        if m["kind"].startswith("incremental_perp"):
            ax.plot(m["x_mm"], m["measured_mm"], "o", color=C_ORANGE, ms=4, mfc="white")
    ax.set_xlabel("‖p_c‖ or step (mm)"); ax.set_ylabel("positional error (mm)"); ax.set_title("(a) M1, T = base_frame⁻¹ (JHU)", loc="left"); ax.legend(fontsize=5.5)
    ax = axs[1]
    for s, c in ((0.1, C_BLUE), (0.5, C_ORANGE), (1.1, C_GREEN)):
        ax.plot(ps * 1e3, [G.m2_error(s, p) * 1e3 for p in ps], color=c, lw=1.5, label=f"s = {s}")
    for m in mrows:
        if m["kind"] == "scale_absolute":
            ax.plot(m["x_mm"], m["measured_mm"], "o", color=C_BLUE, ms=4, mfc="white")
    ax.set_xlabel("distance from origin (mm)"); ax.set_ylabel("error (mm)"); ax.set_title("(b) M2, |1−s|‖p‖", loc="left"); ax.legend(fontsize=6)
    ax = axs[2]
    fs = np.logspace(1, 3, 100)
    for v, c in ((0.02, C_GREEN), (0.05, C_BLUE), (0.1, C_ORANGE)):
        ax.plot(fs, v / fs * 1e3, color=c, lw=1.5, label=f"v = {v*1e3:.0f} mm/s")
    ax.axhline(1.0, color=C_GREY, lw=0.8, ls=":"); ax.axhline(0.5, color=C_GREY, lw=0.8, ls=":")
    ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("command rate f (Hz)"); ax.set_ylabel("ZOH lag bound v/f (mm)"); ax.set_title("(c) M3, eq. (9)", loc="left"); ax.legend(fontsize=6)
    fig.tight_layout()
    fig.savefig(os.path.join(figdir, "fig03_error_model.pdf")); fig.savefig(os.path.join(figdir, "fig03_error_model.png"), dpi=200)
    print("figures written to", figdir)


if __name__ == "__main__":
    main()
